name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
    - name: cache gradle caches
      uses: actions/cache@v4
      env:
        cache-name: cache-gradle-caches
      with:
        path: /home/runner/.gradle/caches/
        key: ${{ runner.os }}-gradle-caches
    - name: build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: ./gradlew build
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          ./app/build/outputs/apk/debug/*.apk
          ./app/build/outputs/bundle/release/*.aab
    # Create release, only for release tags
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: ./app/build/outputs/apk/debug/*.apk,./app/build/outputs/bundle/release/*.aab

  osx-build:
    name: build on osx
    runs-on: macos-14
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: cache AVD
      uses: actions/cache@v4
      env:
        cache-name: cache-avd
      with:
        path: /Users/runner/.android/gradle/avd
        key: ${{ runner.os }}-gradle-avd
    - name: cache gradle caches
      uses: actions/cache@v4
      env:
        cache-name: cache-gradle-caches
      with:
        path: /Users/runner/.gradle/caches/
        key: ${{ runner.os }}-gradle-caches
    - name: build
      run: ./gradlew build
